export const CONFIG = {
  arenaRadius: 28,
  spawnInterval: 8,
  telegraphDuration: 3,
  activeDuration: 2.5,
  starCountMin: 16,
  starCountMax: 20,
  starRadius: 1.35,
  beamHalfWidth: 0.4,
  minStarSpacing: 3.5,
  linkDistanceMin: 4,
  linkDistanceMax: 6.5,
  starsPerStepMin: 1,
  starsPerStepMax: 3,
  extraLinkChance: 0.25,
  spawnClusterRadius: 12,
  maxStarDegree: 3,
  playerThreatChance: 0.8,
  playerRadius: 0.45,
  playerSpeed: 14,
  cameraOffset: { x: 0, y: 11, z: 14 },
  cameraOrbitSensitivity: 0.004,
  cameraPitchMin: 0.25,
  cameraPitchMax: 1.35,
};
